name: Calculator Midterm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov  # Add pytest-cov for coverage reporting
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create logs directory
        run: mkdir -p logs && echo "Logs directory created." >> logs/creation.log || echo "Logs directory already exists." >> logs/creation.log

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run REPL (not in CI)
        run: |
          python calc/repl.py > logs/repl.log 2>&1 || { echo "REPL failed"; cat logs/repl.log; exit 1; }

      - name: Run tests with coverage
        run: |
          pytest --cov=calc --cov=plugins --cov-report=term-missing  # Specify the directories to measure coverage
