name: Calculator Midterm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov  # Add pytest-cov for coverage reporting
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          echo "Dependencies installed."

      - name: Create logs directory
        run: |
          mkdir -p logs || echo "Logs directory already exists."
          echo "Logs directory created or already exists."

      - name: Set PYTHONPATH
        run: |
          echo "Setting PYTHONPATH..."
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
          echo "PYTHONPATH set to $(pwd)."

      - name: Run tests with coverage
        run: |
          echo "Running tests with coverage..."
          pytest --cov=calc --cov=plugins --cov-report=term-missing > logs/test_results.log 2>&1  # Redirect output to log file
          echo "Tests completed."

      - name: Display test results
        run: |
          echo "Displaying test results..."
          cat logs/test_results.log || echo "No test results found."
          echo "Test results displayed."
